### PR TITLE
Changes in LikelihoodDP

### PR DESCRIPTION
**Pull request by filippofiocchi**
I had made some changes, that I think solve the problem. I did't multiply the densities by the weight of the cluster, but i put the code below with the #. On my computer work for now, let me know if it is correct or if I need to modify it. 👍  💯

### CODE REVIEW

**Comment by dm13450** [comment]
Thanks, can you merge the master branch into this please, I fixed the tests last night so will now see if the tests pass for this branch too

**Comment by filippofiocchi** [comment]
Sorry, but actually I have no idea if I merge correctly. I have almost no experience im this things.
I try but I'm not sure that something is changed. I try to merge to your master branch but it says 'already up to date'

**Comment by dm13450** [comment]
You've merged correctly which is great, but the unit tests are failing. 

You can run the tests locally by using cmd+shift+t, or under the build menu and "Test package". 
Once you've fixed the tests I'll get this merged and add you to the contributors.  

And don't worry about not having any experience, we've all got to start somewhere! Let me know if you need any help

**Comment by filippofiocchi** [comment]
I try to run the test, as you said they fail.

>  == Failed tests ================================================================
> -- Error (test_gaussian_fixed_variance.R:4:1): (code run outside of `test_that()`) --
> Error: could not find function "GaussianFixedVarianceMixtureCreate"
> -- Error (test_prior.R:7:3): Prior Function ------------------------------------
> Error: could not find function "PriorFunction"
> -- Error (test_prior_clusters.R:6:3): Prior Clusters ---------------------------
> Error: could not find function "PriorClusters"
> 
> [ FAIL 3 | WARN 0 | SKIP 7 | PASS 514 ]
> Error: Test failures
> Execution halted
> 
> Tests complete

So for fixing the test you mean change the test_gaussian_fixed_variance.R for example, in order to make the test pass?
I also made a Check  that one fails too, but this time it is more releted to my modification because it says :

> > ### ** Examples
> > 
> > dp <- Fit(DirichletProcessGaussian(rnorm(10)), 100)
> Error in rowSums(likelihoodValues) : 
>   'x' must be an array of at least two dimensions
> Calls: Fit -> Fit.default -> LikelihoodDP -> rowSums
> Execution halted
> * checking for unstated dependencies in 'tests' ... OK
> * checking tests ...
>   Running 'testthat.R'
>  ERROR
> Running the tests in 'tests/testthat.R' failed.
> Last 13 lines of output:
>    2. \-dirichletprocess:::Fit.default(dp, 2, progressBar = FALSE)
>    3.   \-dirichletprocess::LikelihoodDP(dpObj)
>    4.     \-base::rowSums(likelihoodValues)
>   -- Error (test_utilities.R:21:3): Burn -----------------------------------------
>   Error: 'x' must be an array of at least two dimensions
>   Backtrace:
>       x
>    1. +-dirichletprocess::Fit(DirichletProcessGaussian(rnorm(10)), 4) test_utilities.R:21:2
>    2. \-dirichletprocess:::Fit.default(...)
>    3.   \-dirichletprocess::LikelihoodDP(dpObj)
>    4.     \-base::rowSums(likelihoodValues)
>   
>   [ FAIL 23 | WARN 0 | SKIP 6 | PASS 436 ]
>   Error: Test failures
>   Execution halted
> * checking for unstated dependencies in vignettes ... OK
> * checking package vignettes in 'inst/doc' ... OK
> * checking running R code from vignettes ...
>   'dirichletprocess.Rnw' using 'UTF-8'... OK
>  OK
> * checking re-building of vignette outputs ... OK
> * checking PDF version of manual ... OK
> * DONE
> Status: 2 ERRORs

Should I also change some files in order to make the tests of the check pass?
If you could give me some hints I will try  to fix the tests. Thank again for the answers and feedback, they help me understand a lot of these new things.

**Comment by dm13450** [comment]
Yeah it is your modification that has broken the tests, so you'll have to re-approach how you sum up the likelihood values. 
`rowSums` works for the multivariate Gaussian but not for the other mixture models it seems.

**Comment by filippofiocchi** [comment]
Ok understood the problem, I'll work on it today and fix it

**Comment by filippofiocchi** [comment]
I fixed the tests and push the changes, let me know if I need to do anything else

**Comment by dm13450** [comment]
Merged, let me know what email you want on the contributors list for the package description. 
Thanks for the work!

**Comment by filippofiocchi** [comment]
filippofiocchi1@gmail.com is ok.
You are welcome 👍

**Pull request merged**
